version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    # Uncomment if using ChromaDB
    # depends_on:
    #   - chromadb
    # 
    # chromadb:
    #   image: chromadb/chroma
    #   ports:
    #     - "8000:8000"
    #   restart: unless-stopped